### ISSUE TITLE
ADFSFarm: Install ADFS Farm without Domain Admins privileges

### ISSUE THREAD

**Issue by anorstrom** [X-Guardian/AdfsDsc#42]
#### Details of the scenario you tried and the problem that is occurring
We would like to install our ADSF Farm without Domain Admins privileges, following the procedure Microsoft provides in https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/deployment/install-ad-fs-delegated-admin. 

We would first manually pre-create an ADFS Farm in Active Directory following these instructions https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/deployment/install-ad-fs-delegated-admin#prepare-ad-1

We would then like to use AdfsDsc, and teh ADFSFarm resource, to create the ADFS Farm like it is being done in https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/deployment/install-ad-fs-delegated-admin#create-the-ad-fs-farm-1. This method requires the parameter -AdminConfiguration, which is currently not supported in AdfsDsc.

#### Suggested solution to the issue
Add the parameter AdminConfiguration, to the ADFSFarm resource. The value must be a hashtable according to documentation https://docs.microsoft.com/en-us/powershell/module/adfs/install-adfsfarm?view=win10-ps.

**Comment by X-Guardian** [comment]
Hi @anorstrom, I have raised PR #43 to add the `AdminConfiguration` property to the `AdfsFarm` resource. Can you test this for me before I merge? Please see [AdfsFarm_gMSA_SQL_Integrated_Delegated_Admin_Config](https://github.com/X-Guardian/AdfsDsc/blob/adfsfarm-adminconfiguration/source/Examples/Resources/AdfsFarm/5-AdfsFarm_gMSA_SQL_Integrated_Delegated_Admin_Config.ps1) for an example showing the `AdminConfiguration` property in use.

**Comment by anorstrom** [comment]
Thank you @X-Guardian !  

I've tested in our Dev and it works good. We use ADFS with WID though, so I didn't test the SQL configuration, but that should not change anything for this switch I think.

**Comment by X-Guardian** [comment]
@anorstrom, I've release AdfsDsc `v1.1.0` to the [PowerShell Gallery](https://www.powershellgallery.com/packages/AdfsDsc/1.1.0) which includes this change.
